# environment setup
language: node_js
node_js:
  - 10
cache: yarn

# setup
before_script: 
  - cd server
  - yarn install

# script
script: yarn test

# after success steps
after_success:
  - yarn codecov
  - cd ..

# ssh setup
addons:
  ssh_known_hosts: rsptn.ddns.net

before_deploy:
  - openssl aes-256-cbc -K $encrypted_bed876356beb_key -iv $encrypted_bed876356beb_iv -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

# deployment
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet server/build/index.js pi@rsptn.ddns.net:/mnt/hdd1/appholder/
  on:
    branch: server
