# cache
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  apt: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
    - ${TRAVIS_BUILD_DIR}/android-sdk/extras/

# environment setup
language: android
dist: trusty
android:
  components:
    - build-tools-29.0.2
    - android-29

# script
script: client/android/gradlew build

after_script: ./list.sh

# deployment
addons:
  ssh_known_hosts: rsptn.ddns.net

before_deploy:
- openssl aes-256-cbc -K $encrypted_bed876356beb_key -iv $encrypted_bed876356beb_iv -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/client/android/app/build/outputs/apk/release/ pi@rsptn.ddns.net:/mnt/hdd1/appholder
  on:
    branch: client/android